version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  # For development only
  # Uncomment to run frontend and backend separately
  # frontend:
  #   image: node:18-alpine
  #   working_dir: /app
  #   command: sh -c "npm install && npm start"
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./app/client:/app
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - app

volumes:
  data: 